 version: '3.7'

 services:
  app:
    build: .
    image: webapi:latest
    ports:
     - 5000:80

  mongo:
    image: mongo:latest
    volumes:
    - ./db-data/mongo/:/data/db
    ports:
    - 27017:27017
