 version: '3.7'

 services:
  app:
    build: .
    image: webapi:latest
    ports:
     - 5000:80

  mongo:
    image: mongo:latest
    volumes:
    - ./db-data/mongo/:/data/db
    ports:
    - 27017:27017
    
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka 
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:9094
      # KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE